bid_api/urls.py
from django.conf.urls import url

from .views import info, badger, create_user, authenticate

app_name = 'bid_api'
urlpatterns = [
    url(r'^user$', info.user_info, name='user'),
    url(r'^me$', info.user_info),
    url(r'^user/(?P<user_id>\d+)$', info.UserInfoView.as_view(), name='user-info-by-id'),
    url(r'^user/(?P<user_id>\d+)/avatar$', info.UserAvatarView.as_view(), name='user-avatar'),
    url(r'^badges/(?P<user_id>\d+)$', info.UserBadgeView.as_view(), name='user-badges-by-id'),
    url(r'^badges/(?P<user_id>\d+)/html$', info.BadgesHTMLView.as_view(), name='user-badges-html'),
    url(r'^badges/(?P<user_id>\d+)/html/(?P<size>[a-z])$', info.BadgesHTMLView.as_view(),
        name='user-badges-html'),
    url(r'^stats$', info.StatsView.as_view(), name='stats'),
    url(r'^badger/grant/(?P<badge>[^/]+)/(?P<email_or_uid>[^/]+)$',
        badger.BadgerView.as_view(action='grant'), name='badger_grant'),
    url(r'^badger/revoke/(?P<badge>[^/]+)/(?P<email_or_uid>[^/]+)$',
        badger.BadgerView.as_view(action='revoke'), name='badger_revoke'),
    url(r'^check-user/(?P<email>[^/]+)$', create_user.CheckUserView.as_view(), name='check_user'),
    url(r'^create-user/?$', create_user.CreateUserView.as_view(), name='create_user'),
    url(r'^authenticate/?$', authenticate.AuthenticateView.as_view(), name='authenticate'),
]

# noinspection PyUnresolvedReferences
from . import signals as _

bid_main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from . import forms
from .views import normal_pages, registration_email, json_api

app_name = 'bid_main'
urlpatterns = [
    url(r'^$', normal_pages.IndexView.as_view(), name='index'),
    url(r'^settings/profile$', normal_pages.ProfileView.as_view(), name='profile'),
    url(r'^login$', normal_pages.LoginView.as_view(), name='login'),
    url(r'^logout$', normal_pages.LogoutView.as_view(next_page='bid_main:about'), name='logout'),
    url(r'^switch/?$', normal_pages.SwitchUserView.as_view(), name='switch_user'),
    url(r'^switch/(?P<switch_to>.+)$', normal_pages.SwitchUserView.as_view(), name='switch_user'),
    url(r'^privacy-policy/agree$', normal_pages.PrivacyPolicyAgreeView.as_view(),
        name='privacy_policy_agree'),

    url(r'^badge-toggle-private', json_api.BadgeTogglePrivateView.as_view(),
        name='badge_toggle_private'),

    url('^change$',
        auth_views.PasswordChangeView.as_view(
            form_class=forms.PasswordChangeForm,
            success_url=reverse_lazy('bid_main:password_change_done')),
        name='password_change'),
    url('^change-password/done$', auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    url(r'^password_reset/$',
        auth_views.PasswordResetView.as_view(
            form_class=forms.PasswordResetForm,
            success_url=reverse_lazy('bid_main:password_reset_done')),
        name='password_reset'),
    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('bid_main:password_reset_complete')),
        name='password_reset_confirm'),
    url(r'^password_reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    # Source of registration machinery:
    # http://musings.tinbrain.net/blog/2014/sep/21/registration-django-easy-way/
    url(r'^register/$', registration_email.RegistrationView.as_view(), name='register'),
    url(r'^register/signed-up/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/initial_signed_up.html'),
        name='register-done'),
    url(
        r'^register/password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        registration_email.InitialSetPasswordView.as_view(), name='register-confirm'),
    url(r'^register/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/registration_complete.html'),
        name='register-complete'),

    url(r'^confirm-email/start$',
        registration_email.ConfirmEmailView.as_view(),
        name='confirm-email'),
    url(r'^confirm-email/start-change$', registration_email.ConfirmEmailView.as_view(
        template_name='bid_main/confirm_email/change.html'), name='confirm-email-change'),
    url(r'^confirm-email/cancel-change$', registration_email.CancelEmailChangeView.as_view(),
        name='cancel-email-change'),
    url(r'^confirm-email/sent$',
        registration_email.ConfirmEmailSentView.as_view(),
        name='confirm-email-sent'),
    url(r'^confirm-email/verified/(?P<info>[^/]+)/(?P<hmac>[^/]+)$',
        registration_email.ConfirmEmailVerifiedView.as_view(),
        name='confirm-email-verified'),
    url(r'^confirm-email/poll$',
        registration_email.ConfirmEmailPollView.as_view(),
        name='confirm-email-poll'),
]

# Only enable this on a dev server:
if settings.DEBUG:
    from .views import testviews

    urlpatterns += [
        url(r'^debug/email-changed$', testviews.test_mail_email_changed),
        url(r'^debug/email-verify$', testviews.test_mail_verify_address),
        url(r'^error/(?P<code>\d+)$', testviews.test_error),
    ]

mykdeorg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.flatpages import views as fp_views
from django.conf import settings
import django.contrib.staticfiles.views

import bid_main.views.errors as error_views

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include('loginas.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('bid_addon_support.urls', namespace='addon_support')),
    url(r'^oauth/', include('mykdeorg.oauth2_urls', namespace='oauth2_provider')),
    url(r'^api/', include('bid_api.urls', namespace='bid_api')),
    url(r'', include('bid_main.urls', namespace='bid_main')),
]

handler400 = error_views.ErrorView.as_view(template_name='errors/400.html', status=400)
handler403 = error_views.ErrorView.as_view(template_name='errors/403.html', status=403)
handler404 = error_views.ErrorView.as_view(template_name='errors/404.html', status=404)
handler500 = error_views.ErrorView.as_view(template_name='errors/500.html', status=500)

if settings.DEBUG:
    import debug_toolbar

    settings.STATICFILES_FINDERS.insert(0, 'bid_main.devserver_support.MediaFinder')
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(rf'^media/(?P<path>.*)$', django.contrib.staticfiles.views.serve),
    ]

urlpatterns += [
    # Flatpages must be last!
    url(r'^(?P<url>.*/?)', fp_views.flatpage),
]

bid_main/views/errors.py
"""Error handlers."""

from django.http import HttpResponse
from django.views.generic import TemplateView


class ErrorView(TemplateView):
    """Renders an error page."""
    # TODO(Sybren): respond as JSON when this is an XHR.

    status = 500

    def dispatch(self, request=None, *args, **kwargs):
        if request is None or request.method in {'HEAD', 'OPTIONS'}:
            # Don't render templates in this case.
            return HttpResponse(status=self.status)

        # We allow any method for this view,
        response = self.render_to_response(self.get_context_data(**kwargs))
        response.status_code = self.status
        return response


def csrf_failure(request, reason=""):
    import django.views.csrf

    return django.views.csrf.csrf_failure(request,
                                          reason=reason,
                                          template_name='errors/403_csrf.html')

bid_main/views/json_api.py
"""JSON views that aren't real API calls.

Those are used by regular views, and contrary to real API calls (which would
live in bid_api) expect authentication via the sessions and CSRF checks rather
than via bearer tokens.
"""

import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import View

from .. import models

log = logging.getLogger(__name__)


class BadgeTogglePrivateView(LoginRequiredMixin, View):
    """JSON endpoint that toggles 'is_private' flag for badges."""

    def post(self, request, *args, **kwargs) -> JsonResponse:
        try:
            badge_name = request.POST['badge_name']
        except KeyError:
            return JsonResponse({'_message': 'no badge name given'}, status=422)

        role: models.Role = get_object_or_404(models.Role.objects, name=badge_name)
        if request.user.private_badges.filter(id=role.id).count():
            request.user.private_badges.remove(role)
            now_private = False
        else:
            request.user.private_badges.add(role)
            now_private = True

        return JsonResponse({'is_private': now_private})

bid_main/views/mixins.py
"""Mix-in classes for views."""
import logging
import urllib.parse

from django.urls import reverse_lazy

log = logging.getLogger(__name__)


class PageIdMixin:
    page_id = ''

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['page_id'] = self.page_id
        return ctx


class RedirectToPrivacyAgreeMixin:
    privacy_policy_agree_url = reverse_lazy('bid_main:privacy_policy_agree')

    def get_success_url(self):
        """Return the user-originating redirect URL if it's safe."""

        regular_redir_url = super().get_success_url()
        if not self.request.user.must_pp_agree:
            return regular_redir_url

        # User must agree to privacy policy first before being redirected.
        next_url_qs = urllib.parse.urlencode({
            'next': regular_redir_url,
        })
        redirect_to = f'{self.privacy_policy_agree_url}?{next_url_qs}'
        log.debug('Directing user to %s', redirect_to)
        return redirect_to

bid_main/views/oauth2.py
"""Our own hooks into the OAuth2 flow."""

import logging

from django.shortcuts import render
from oauth2_provider import views as base_views
from oauth2_provider.models import get_application_model

from bid_main import forms

log = logging.getLogger(__name__)
OAuth2Application = get_application_model()


class AuthorizationView(base_views.AuthorizationView):
    """Refuses to authorize user with unconfirmed email."""

    log = log.getChild('AuthorizationView')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated and not request.user.has_confirmed_email:
            return self.force_email_confirm(request)
        return super().get(request, *args, **kwargs)

    def force_email_confirm(self, request):
        """Disrupt the OAuth2 flow by forcing the user to confirm their email."""

        # This copies some stuff from the superclass to figure out the OAuth2 application.
        _, credentials = self.validate_authorization_request(request)
        application = OAuth2Application.objects.get(client_id=credentials["client_id"])

        self.log.info('Forcing user to confirm email before allowing OAuth2 flow with app %r.',
                      application.name)

        qs = request.META.get('QUERY_STRING', '')
        requested = f'{request.path}?{qs}' if qs else request.path
        self.log.debug('Their original URL was %r', requested)

        ctx = {
            'form': forms.ConfirmEmailStartForm(
                {'next_url': requested,
                 'next_name': application.name}),
            'next_name': application.name,
            'user': request.user,
        }
        return render(request, 'bid_main/confirm_email/start_for_oauth.html', ctx)

bid_main/views/testviews.py
"""Views for testing certain functionality."""


def test_mail_email_changed(request):
    """View for designing the email without having to send it all the time."""
    from django.http import HttpResponse
    from ..email import construct_email_changed_mail

    email_body_html, *_ = construct_email_changed_mail(request.user, 'old@email.nl')

    return HttpResponse(email_body_html)


def test_mail_verify_address(request):
    """View for designing the email without having to send it all the time."""
    from django.http import HttpResponse
    from ..email import construct_verify_address

    email_body_html, *_ = construct_verify_address(request.user, request.scheme)
    return HttpResponse(email_body_html)


def test_error(request, code):
    from django.core import exceptions
    from django.http import response, Http404

    codes = {
        403: exceptions.PermissionDenied,
        404: Http404,
        500: exceptions.ImproperlyConfigured,
    }
    try:
        exc = codes[int(code)]
    except KeyError:
        return response.HttpResponse(f'error test for code {code}', status=int(code))
    else:
        raise exc(f'exception test for code {code}')

templates/bid_main/about.html
{% extends 'layout.html' %}
{% block page_title %}About My KDE{% endblock %}
{% block body %}
{% block before_about_bid %}{% endblock %}
<div class="bid box about">
  <h3>Technical Assistance</h3>
  <p>
    For any issue or request regarding your 'My KDE' account, such as merging accounts or fixing an
    invalid email address, get in touch with sysadmin at kde.org. We will help you right away!
  </p>
</div>{% block after_about_bid %}{% endblock %}
{% endblock %}

templates/bid_main/index.html
{% extends 'layout.html' %}

{% load static %}
{% load avatar badges %}

{% block page_title %}
  {% if user.full_name %}
    {{user.full_name}}'s
  {% else %}
    Your
  {% endif %}
  Profile
{% endblock %}

{% block header %}
  <div class="bg-light py-3 mb-3 border-bottom">
    <div class="container">
      <div class="row col-md-10 mx-auto">
        <div class="col-auto my-auto">
          {% avatar %}
        </div>
        <div class="col">
          <h2>
            {% if user.full_name %}
              {{ user.full_name }}
            {% else %}
              <a href="{% url 'bid_main:profile' %}">Name missing. Complete your profile</a>
            {% endif %}
          </h2>
          <p><strong>Username:</strong> "{{ user.nickname }}"</p>
          {% if user.email_change_preconfirm %}
            <p class="bg-warning p-1">
              A change from {{ user.email }} to {{ user.email_change_preconfirm }} is pending.<br/><a href="javascript:$('#cancel_email_change').submit()">Cancel this change</a> or <a href="{% url 'bid_main:confirm-email-change' %}">re-send confirmation email</a>.
            </p>
          {% else %}
            <p><strong>Email: </strong>{{ user.email }}</p>
          {% endif %}
          {% if show_confirm_address %}
            <p class="bg-warning p-1">
              <a href="{% url 'bid_main:confirm-email' %}">Confirm your email address</a> to unleash the full power of KDE Accounts.
            </p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block body %}
  <section>
    <h2>Actions</h2>
    
    <p>
      <a class="btn btn-secondary mt-2" href="{% url 'bid_main:password_change' %}">Change Password</a>
    </p>
    <p>
      <a class="btn btn-secondary mt-2" href="{% url 'bid_main:profile' %}">Edit profile</a>
    </p>
    
    <form id="cancel_email_change" action="{% url 'bid_main:cancel-email-change' %}" method="POST">{% csrf_token %}</form>
  </section>
  
  <section class="mt-3">
    <h3>Your Badges</h3>
    {% with badges=user.all_badges %}
      {% if badges %}
        <ul class="badges">
          {% for badge in badges %}
            {% render_badge badge %}
          {% endfor %}
        </ul>
        <p>
          You have earned {{ badges|length }} badge{{ badges|pluralize }}. If you do not want to show
          those badges on connected websites, you can mark them as private.
        </p>
      {% else %}
        <p>
          You don't have any badges. You can earn badges in various ways, for example by (tbd.)
        </p>
      {% endif %}
    {% endwith %}
  </section>
  
  <section class="mt-3">
    <h3>Your KDE Apps</h3>
    {% if apps %}
      <p>
        You have granted the following applications access to your KDE Accounts; in other
        words, you used your KDE Accounts to log in there. Click on the cross to remove
        all authentication tokens for those apps, effectively logging you out there.
     </p>
    {% else %}
      <p>
        You have not granted any applications access to your KDE Accounts; in other words,
        you have not used your KDE Accounts to log in anywhere yet. When you do, this is
        the place where you will be able to revoke that access from those applications.
      </p>
    {% endif %}
    <form id="revokeform" method="post" action="">
      {% csrf_token %}
      {{ form.app_id }}
      {{ form.errors }}
    </form>
    <ul>
      {% for app in apps %}
      <li>
        <div class="app-info">
          {{ app }}
          {% if app.url %}<a class="app-url" href="{{ app.url }}" target="_blank">{{ app.url }}</a>{% endif %}
        </div>
        <a class="app-revoke" title="Remove {{ app }} authentication token" href="javascript:revoke({{ app.id }})">Revoke Access</a>
      </li>
      {% endfor %}
    </ul>
  </section>
{% endblock %}

{% block footer_scripts %}
  <script src="{% static 'assets_vendor/js/toastr.min.js' %}"></script>
  <script src="{% static 'assets_vendor/js/bootstrap-toggle.min.js' %}"></script>
  <script src="{% static 'assets_vendor/js/js.cookie.min.js' %}"></script>
  <script src="{% static 'assets/js/notifications.min.js' %}"></script>
  <script>
    function toggle_badge_privacy(event) {
      let badge_name = event.target.dataset.badgeName;
  
      $.post("{% url 'bid_main:badge_toggle_private'  %}", {
        csrfmiddlewaretoken: Cookies.get('csrftoken'),
        badge_name: badge_name,
      })
      .fail(function (error) {
        toastr.error(xhrErrorResponseMessage(error), 'Unable to toggle badge privacy');
      })
      .done(function (response) {
        let $badge = $('li.badge.' + badge_name);
        if (response.is_private) {
          $badge.addClass('private');
        } else {
          $badge.removeClass('private');
        }
      });
    }
    $(function() {
      $("input[data-toggle]").bootstrapToggle();
      $("input[type='checkbox'][data-badge-name]").change(toggle_badge_privacy);
    })
  </script>
{% endblock %}

templates/bid_main/login.html
{% extends 'bid_main/about.html' %}
{% load static %}

{% block page_title %}Log in KDE Accounts{% endblock %}

{% block header %}
  <div class="bg-light py-3 mb-3 border-bottom">
    <div class="container">
      <div class="row col-md-10 mx-auto">
        <div class="col-auto">
            <img src="{% static "/assets/img/users.svg" %}" alt="KDE Accounts logo" style="min-width: 200px" />
        </div>
        <div class="col my-auto">
          <h2>Welcome to KDE Accounts</h2>
          <h5>KDE Accounts is a unified login system that will give you in the future access to a large number of services around KDE.</h5>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block before_about_bid %}
<div>
  {% if is_oauth_flow %}
    <h1>Please sign in to continue to <span style="white-space: nowrap">{{ oauth_app.name }}</span></h1>
    <p>{{ oauth_app.name }} uses KDE Accounts to authenticate users.</p>
  {% else %}
    <h1>Login in KDE Accounts</h1>
  {% endif %}
  <form role="login" action="" method="POST">
    {% csrf_token %}
    <fieldset>
      <!-- Email input-->
      <div class="form-group">
        <label for="id_username">Email address</label>
        {{ form.username }}
      </div>
      <!-- Password input-->
      <div class="form-group">
        <label for="id_password">Password</label>
        {{ form.password }}
      </div>
      {% if form.errors %}
      <p class="text-danger">Your username and password didn't match. Please try again.</p>
      <p><a href="{% url 'bid_main:password_reset' %}">Lost your password?</a></p>
      {% endif %}
      <button class="btn btn-success" id="register">Sign in</button>
    </fieldset>
    <hr/>
    <p><a href="{% url 'bid_main:register' %}">Create a new account</a></p>
    <p><a href="{% url 'bid_main:password_reset' %}">Recover password</a></p>
  </form>
</div>
{% endblock %}

templates/bid_main/privacy_policy_agree.html
{% extends 'layout.html' %}
{% block page_title %}Privacy Policy{% endblock %}
{% block privacy_policy_banner %}{% endblock %}
{% block body %}
<div>
  <h1>Privacy Policy</h1>
  <p>
    Before you continue to use our service, please read and agree
    to <a href="/privacy-policy" target="_blank">our Privacy Policy</a>
    (the link opens in a new tab).
  </p>
  <form role="login" action="" method="POST">
    {% csrf_token %}
    {{ form.next_url }}
    <fieldset>
        <div class="form-check">
            {{ form.agree }}
            <label for="{{ form.agree.id_for_label }}">I have read and agree to the privacy policy as linked above.</label>
        </div>
         <button class="btn btn-success" type="submit">Submit &amp; Continue</button>{% if may_skip and form.next_url.value %}<a class="button btn-warning" style="margin-left: 1em" href="{{ form.next_url.value }}">» Skip for now</a>{% endif %}
    </fieldset>
  </form>
  <h2 class="mt-2">Our policy in three points</h2>
  <ul>
    <li>We value your privacy.</li>
    <li>
      We only ask for personal information needed to run this service,
      namely your full name, email address, and nickname.
    </li>
    <li>
      We will not share your personal information with third parties,
      unless you use KDE Identity to log in at a third-party website.
    </li>
  </ul>
  <p class="note">
    Note that these three points do not consistute a legally binding text. For that,
    read our <a href="/privacy-policy" target="_blank">Privacy Policy</a>.
  </p>
</div>
{% endblock %}

templates/bid_main/profile.html
{% extends 'layout.html' %}
{% load avatar %}
{% block page_title %}Edit Your Profile -- KDE Identity{% endblock %}
{% block header %}
<style>
  .avatar-editor {
  	align-items: center;
  	justify-content: center;
  	padding-right: 2mm;
  }
  .avatar-editor img {
  	margin-right: 2mm;
  	border-right: thin solid var(--border-color);
  }
</style>
{% endblock %}
{% block body %}
<div class="bid box">
  <h2>Edit Profile</h2>
  <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <fieldset>
      <div class="row">
        <div class="col-md-9">
          <!-- Full name input-->
          <label class="control-label">Full Name</label>
          <div class="input-group {% if not user.full_name %}form-required{% endif %}">{{ form.full_name }}</div>{{ form.full_name.errors }}
          <!-- Email display-->
          <label class="control-label">Email</label>
          <div class="input-group">{{ form.email }}</div>{% if user.email_change_preconfirm %}
          <p class="help-text">A change to {{ user.email_change_preconfirm }} is already pending.<br/><a href="javascript:$('#cancel_email_change').submit()">Cancel this change</a> or <a href="{% url 'bid_main:confirm-email-change' %}">re-send confirmation email</a>.
          </p>{% endif %}
          <!-- Nickname input-->
          <label class="control-label">Nickname</label>
          <div class="input-group">{{ form.nickname }}</div>{{ form.nickname.errors }}
          {{ form.non_field_errors }}
          <!-- Avatar input-->
          <label class="control-label">Avatar</label>
          <div class="input-group avatar-editor">
            {% avatar size=64 %}
            <input class="form-control-file mt-2" id="avatar-file-input" type="file" name="avatar"/>
            <label class="mt-2">
              <input type="checkbox" name="avatar-clear"/>Clear
            </label>
          </div>{{ form.avatar.errors }}
        </div>
        <div class="col-md-3">
          <div class="bid-user profile">
            <div class="bid-user-info">{% avatar %}</div>
          </div>
        </div>
      </div>
      <div class="bid-cta">
        <button class="btn btn-filled-success btn-success" type="submit">Save Changes</button>
        <a class="btn btn-danger ml-2" href="{% url 'bid_main:index' %}">Discard Changes</a>
        <a class="btn btn-grey ml-2" href="{% url 'bid_main:password_change' %}">Change Password</a>
      </div>
    </fieldset>
  </form>
  <form id="cancel_email_change" action="{% url 'bid_main:cancel-email-change' %}" method="POST">{% csrf_token %}</form>
  {% if user.is_staff %}
      <div class="bid-links"><a href="{% url 'admin:bid_main_user_change' user.id %}">Edit account in admin</a></div>
  {% endif %}
</div>{% endblock %}

templates/bid_main/switch_user.html
{% extends 'layout.html' %}
{% load avatar %}
{% block page_title %}Switch KDE Identity user{% endblock %}
{% block body %}
<div class="bid box"><small>You are currently logged in as</small>
  <div class="bid-user"><a href="{% url 'bid_main:index' %}">{% avatar %}</a>
    <div class="bid-user-info">{% if user.full_name %}<a href="{% url 'bid_main:index' %}">
        <h3>{{ user.full_name }}</h3></a>
      <p>{{ user.email }}</p>{% else %}
      <h3><a class="danger" href="{% url 'bid_main:profile' %}">Please specify your full name</a></h3>
      <p>{{ user.email }}</p>{% endif %}
    </div>
  </div>
  <hr/>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>Login as someone else</h2><br/>
      <form role="login" action="" method="POST" name="login_user_form">{% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        <fieldset>
          <!-- Email input-->
          <div class="input-group">{{ form.username }}</div>
          <!-- Password input-->
          <div class="input-group">{{ form.password }}</div>{% if form.errors %}
          <p class="text-danger">Your username and password didn't match. Please try again.</p>
          <p><a href="{% url 'bid_main:password_reset' %}">Lost your password?</a></p>{% endif %}
          <div class="bid-cta">
            <button class="btn-success" id="register">Sign in</button>
          </div>
        </fieldset>
      </form>
      <hr/>
      <div class="bid-links"><a href="{% url 'bid_main:register' %}">Create a new account</a><a href="{% url 'bid_main:password_reset' %}">Recover password</a></div>
    </div>
  </div>
</div>{% endblock %}

templates/bid_main/user_register_form.html
{% extends 'layout.html' %}
{% load trans from i18n %}
{% load static %}
{% block page_title %}
Register your KDE Identity
{% endblock %}
{% block body %}
<div class="bid box">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="bid-header">
        <h1>Get Your Own KDE Identity</h1>
      </div>
      <form role="register" action="" method="POST" name="register_user_form">{% csrf_token %}
        <fieldset>
          <!-- Full name input-->
          <label class="control-label" for="{{ form.full_name.id_for_label }}">Full Name</label>
          <div class="input-group">{{ form.full_name }}</div>{{ form.full_name.errors }}
          <!-- Email input-->
          <label class="control-label" for="{{ form.email.id_for_label }}">Email</label>
          <div class="input-group">{{ form.email }}</div>{{ form.email.errors }}
          <!-- Nickname input-->
          <label class="control-label" for="{{ form.nickname.id_for_label }}">Nickname</label>
          <div class="input-group">{{ form.nickname }}</div>{{ form.nickname.errors }}
          <p>We will send you an email with instructions to set a password.</p>{{ form.non_field_errors }}
        </fieldset>
        <div class="bid-cta">
          <button class="btn btn-success" id="register"><i class="icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512" height="30" >
                <path d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z"></path>
              </svg></i>Create Account</button>
        </div>
        <hr/>
        <div class="bid-links"><a href="{% url 'bid_main:login' %}">Already have an account?</a></div>
      </form>
    </div>
  </div>
</div>{% endblock %}