bid_api/urls.py
from django.conf.urls import url

from .views import info, badger, create_user, authenticate

app_name = 'bid_api'
urlpatterns = [
    url(r'^user$', info.user_info, name='user'),
    url(r'^me$', info.user_info),
    url(r'^user/(?P<user_id>\d+)$', info.UserInfoView.as_view(), name='user-info-by-id'),
    url(r'^user/(?P<user_id>\d+)/avatar$', info.UserAvatarView.as_view(), name='user-avatar'),
    url(r'^badges/(?P<user_id>\d+)$', info.UserBadgeView.as_view(), name='user-badges-by-id'),
    url(r'^badges/(?P<user_id>\d+)/html$', info.BadgesHTMLView.as_view(), name='user-badges-html'),
    url(r'^badges/(?P<user_id>\d+)/html/(?P<size>[a-z])$', info.BadgesHTMLView.as_view(),
        name='user-badges-html'),
    url(r'^stats$', info.StatsView.as_view(), name='stats'),
    url(r'^badger/grant/(?P<badge>[^/]+)/(?P<email_or_uid>[^/]+)$',
        badger.BadgerView.as_view(action='grant'), name='badger_grant'),
    url(r'^badger/revoke/(?P<badge>[^/]+)/(?P<email_or_uid>[^/]+)$',
        badger.BadgerView.as_view(action='revoke'), name='badger_revoke'),
    url(r'^check-user/(?P<email>[^/]+)$', create_user.CheckUserView.as_view(), name='check_user'),
    url(r'^create-user/?$', create_user.CreateUserView.as_view(), name='create_user'),
    url(r'^authenticate/?$', authenticate.AuthenticateView.as_view(), name='authenticate'),
]

# noinspection PyUnresolvedReferences
from . import signals as _

bid_main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from . import forms
from .views import normal_pages, registration_email, json_api

app_name = 'bid_main'
urlpatterns = [
    url(r'^$', normal_pages.IndexView.as_view(), name='index'),
    url(r'^settings/profile$', normal_pages.ProfileView.as_view(), name='profile'),
    url(r'^login$', normal_pages.LoginView.as_view(), name='login'),
    url(r'^logout$', normal_pages.LogoutView.as_view(next_page='bid_main:about'), name='logout'),
    url(r'^switch/?$', normal_pages.SwitchUserView.as_view(), name='switch_user'),
    url(r'^switch/(?P<switch_to>.+)$', normal_pages.SwitchUserView.as_view(), name='switch_user'),
    url(r'^privacy-policy/agree$', normal_pages.PrivacyPolicyAgreeView.as_view(),
        name='privacy_policy_agree'),

    url(r'^badge-toggle-private', json_api.BadgeTogglePrivateView.as_view(),
        name='badge_toggle_private'),

    url('^change$',
        auth_views.PasswordChangeView.as_view(
            form_class=forms.PasswordChangeForm,
            success_url=reverse_lazy('bid_main:password_change_done')),
        name='password_change'),
    url('^change-password/done$', auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    url(r'^password_reset/$',
        auth_views.PasswordResetView.as_view(
            form_class=forms.PasswordResetForm,
            success_url=reverse_lazy('bid_main:password_reset_done')),
        name='password_reset'),
    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('bid_main:password_reset_complete')),
        name='password_reset_confirm'),
    url(r'^password_reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    # Source of registration machinery:
    # http://musings.tinbrain.net/blog/2014/sep/21/registration-django-easy-way/
    url(r'^register/$', registration_email.RegistrationView.as_view(), name='register'),
    url(r'^register/signed-up/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/initial_signed_up.html'),
        name='register-done'),
    url(
        r'^register/password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        registration_email.InitialSetPasswordView.as_view(), name='register-confirm'),
    url(r'^register/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/registration_complete.html'),
        name='register-complete'),

    url(r'^confirm-email/start$',
        registration_email.ConfirmEmailView.as_view(),
        name='confirm-email'),
    url(r'^confirm-email/start-change$', registration_email.ConfirmEmailView.as_view(
        template_name='bid_main/confirm_email/change.html'), name='confirm-email-change'),
    url(r'^confirm-email/cancel-change$', registration_email.CancelEmailChangeView.as_view(),
        name='cancel-email-change'),
    url(r'^confirm-email/sent$',
        registration_email.ConfirmEmailSentView.as_view(),
        name='confirm-email-sent'),
    url(r'^confirm-email/verified/(?P<info>[^/]+)/(?P<hmac>[^/]+)$',
        registration_email.ConfirmEmailVerifiedView.as_view(),
        name='confirm-email-verified'),
    url(r'^confirm-email/poll$',
        registration_email.ConfirmEmailPollView.as_view(),
        name='confirm-email-poll'),
]

# Only enable this on a dev server:
if settings.DEBUG:
    from .views import testviews

    urlpatterns += [
        url(r'^debug/email-changed$', testviews.test_mail_email_changed),
        url(r'^debug/email-verify$', testviews.test_mail_verify_address),
        url(r'^error/(?P<code>\d+)$', testviews.test_error),
    ]

mykdeorg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.flatpages import views as fp_views
from django.conf import settings
import django.contrib.staticfiles.views

import bid_main.views.errors as error_views

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include('loginas.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('bid_addon_support.urls', namespace='addon_support')),
    url(r'^oauth/', include('mykdeorg.oauth2_urls', namespace='oauth2_provider')),
    url(r'^api/', include('bid_api.urls', namespace='bid_api')),
    url(r'', include('bid_main.urls', namespace='bid_main')),
]

handler400 = error_views.ErrorView.as_view(template_name='errors/400.html', status=400)
handler403 = error_views.ErrorView.as_view(template_name='errors/403.html', status=403)
handler404 = error_views.ErrorView.as_view(template_name='errors/404.html', status=404)
handler500 = error_views.ErrorView.as_view(template_name='errors/500.html', status=500)

if settings.DEBUG:
    import debug_toolbar

    settings.STATICFILES_FINDERS.insert(0, 'bid_main.devserver_support.MediaFinder')
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(rf'^media/(?P<path>.*)$', django.contrib.staticfiles.views.serve),
    ]

urlpatterns += [
    # Flatpages must be last!
    url(r'^(?P<url>.*/?)', fp_views.flatpage),
]

bid_main/views/errors.py
"""Error handlers."""

from django.http import HttpResponse
from django.views.generic import TemplateView


class ErrorView(TemplateView):
    """Renders an error page."""
    # TODO(Sybren): respond as JSON when this is an XHR.

    status = 500

    def dispatch(self, request=None, *args, **kwargs):
        if request is None or request.method in {'HEAD', 'OPTIONS'}:
            # Don't render templates in this case.
            return HttpResponse(status=self.status)

        # We allow any method for this view,
        response = self.render_to_response(self.get_context_data(**kwargs))
        response.status_code = self.status
        return response


def csrf_failure(request, reason=""):
    import django.views.csrf

    return django.views.csrf.csrf_failure(request,
                                          reason=reason,
                                          template_name='errors/403_csrf.html')

bid_main/views/json_api.py
"""JSON views that aren't real API calls.

Those are used by regular views, and contrary to real API calls (which would
live in bid_api) expect authentication via the sessions and CSRF checks rather
than via bearer tokens.
"""

import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import View

from .. import models

log = logging.getLogger(__name__)


class BadgeTogglePrivateView(LoginRequiredMixin, View):
    """JSON endpoint that toggles 'is_private' flag for badges."""

    def post(self, request, *args, **kwargs) -> JsonResponse:
        try:
            badge_name = request.POST['badge_name']
        except KeyError:
            return JsonResponse({'_message': 'no badge name given'}, status=422)

        role: models.Role = get_object_or_404(models.Role.objects, name=badge_name)
        if request.user.private_badges.filter(id=role.id).count():
            request.user.private_badges.remove(role)
            now_private = False
        else:
            request.user.private_badges.add(role)
            now_private = True

        return JsonResponse({'is_private': now_private})

bid_main/views/mixins.py
"""Mix-in classes for views."""
import logging
import urllib.parse

from django.urls import reverse_lazy

log = logging.getLogger(__name__)


class PageIdMixin:
    page_id = ''

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['page_id'] = self.page_id
        return ctx


class RedirectToPrivacyAgreeMixin:
    privacy_policy_agree_url = reverse_lazy('bid_main:privacy_policy_agree')

    def get_success_url(self):
        """Return the user-originating redirect URL if it's safe."""

        regular_redir_url = super().get_success_url()
        if not self.request.user.must_pp_agree:
            return regular_redir_url

        # User must agree to privacy policy first before being redirected.
        next_url_qs = urllib.parse.urlencode({
            'next': regular_redir_url,
        })
        redirect_to = f'{self.privacy_policy_agree_url}?{next_url_qs}'
        log.debug('Directing user to %s', redirect_to)
        return redirect_to

bid_main/views/oauth2.py
"""Our own hooks into the OAuth2 flow."""

import logging

from django.shortcuts import render
from oauth2_provider import views as base_views
from oauth2_provider.models import get_application_model

from bid_main import forms

log = logging.getLogger(__name__)
OAuth2Application = get_application_model()


class AuthorizationView(base_views.AuthorizationView):
    """Refuses to authorize user with unconfirmed email."""

    log = log.getChild('AuthorizationView')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated and not request.user.has_confirmed_email:
            return self.force_email_confirm(request)
        return super().get(request, *args, **kwargs)

    def force_email_confirm(self, request):
        """Disrupt the OAuth2 flow by forcing the user to confirm their email."""

        # This copies some stuff from the superclass to figure out the OAuth2 application.
        _, credentials = self.validate_authorization_request(request)
        application = OAuth2Application.objects.get(client_id=credentials["client_id"])

        self.log.info('Forcing user to confirm email before allowing OAuth2 flow with app %r.',
                      application.name)

        qs = request.META.get('QUERY_STRING', '')
        requested = f'{request.path}?{qs}' if qs else request.path
        self.log.debug('Their original URL was %r', requested)

        ctx = {
            'form': forms.ConfirmEmailStartForm(
                {'next_url': requested,
                 'next_name': application.name}),
            'next_name': application.name,
            'user': request.user,
        }
        return render(request, 'bid_main/confirm_email/start_for_oauth.html', ctx)

bid_main/views/testviews.py
"""Views for testing certain functionality."""


def test_mail_email_changed(request):
    """View for designing the email without having to send it all the time."""
    from django.http import HttpResponse
    from ..email import construct_email_changed_mail

    email_body_html, *_ = construct_email_changed_mail(request.user, 'old@email.nl')

    return HttpResponse(email_body_html)


def test_mail_verify_address(request):
    """View for designing the email without having to send it all the time."""
    from django.http import HttpResponse
    from ..email import construct_verify_address

    email_body_html, *_ = construct_verify_address(request.user, request.scheme)
    return HttpResponse(email_body_html)


def test_error(request, code):
    from django.core import exceptions
    from django.http import response, Http404

    codes = {
        403: exceptions.PermissionDenied,
        404: Http404,
        500: exceptions.ImproperlyConfigured,
    }
    try:
        exc = codes[int(code)]
    except KeyError:
        return response.HttpResponse(f'error test for code {code}', status=int(code))
    else:
        raise exc(f'exception test for code {code}')

templates/bid_main/confirm_email/base.html
{% extends 'layout.html' %}
{% block page_title %}Confirm your email address{% endblock %}
{% block body %}
<div class="bid box">{% block confirm_email_body %}{% endblock %}</div>{% endblock %}

templates/bid_main/confirm_email/change.html
{% extends 'bid_main/confirm_email/form.html' %}
{% block confirm_email_above_form %}
<h1>Confirm your new email address</h1>{% endblock %}

templates/bid_main/confirm_email/form.html
{% extends 'bid_main/confirm_email/base.html' %}
{% block confirm_email_body %}
    {% block confirm_email_above_form %}{% endblock %}
<p class="text-primary">
  Is your address {{ user.email_to_confirm }}?
  
</p>
<form action="{% url 'bid_main:confirm-email' %}" method="POST">
  {% csrf_token %}
  {{ form.next_url }}
  {{ form.next_name }}
  <div class="bid-cta"><a class="btn" href="javascript:cancel()">
      {% if user.email_change_preconfirm %}
      Cancel Email Change
      {% else %}
      Edit address
      {% endif %}</a>
    <button class="btn btn-success" type="submit">Yes that is correct</button>
  </div>
</form>
<form id="cancel_email_change" action="{% url 'bid_main:cancel-email-change' %}" method="POST">{% csrf_token %}</form>{% endblock %}
{% block footer_scripts %}
<script>
  function cancel() {
  	{% if user.email_change_preconfirm %}
  	$('#cancel_email_change').submit();
  	{% else %}
  	window.location = "{% url 'bid_main:index' %}";
  	{% endif %}
  }
</script>{% endblock %}

templates/bid_main/confirm_email/integrity-error.html
{% extends 'bid_main/confirm_email/base.html' %}
{% block confirm_email_body %}
<h1 class="text-danger">Error confirming your email</h1>
<p>
  There was a database error while we tried to save your confirmed email address: {{ error }}
  
</p>
<p>
  This could mean you tried to change your email address, but someone else already registered
  that address in the mean time. Please contact us at
  <a href="mailto:cloudsupport@blender.org">cloudsupport@blender.org</a> if this error persist.
  
</p>
<p>
  If you want you can try again to see if that helps.
  
</p>
<form action="{% url 'bid_main:confirm-email' %}" method="POST">{% csrf_token %}
  <div class="bid-cta"><a class="btn" href="{% url 'bid_main:index' %}">Back to the dashboard</a>
    <button class="btn btn-success" type="submit">Try again</button>
  </div>
</form>{% endblock %}

templates/bid_main/confirm_email/sent.html
{% extends 'bid_main/confirm_email/base.html' %}
{% block confirm_email_body %}
<h1>Confirm your email address</h1>
<p>We have sent an email with instructions to {{ user.email_to_confirm }}.<br/>
  Please check your inbox and spam folder!
  
</p>
<div class="text-success bg-success" id="poll_ok" style="display: none">
  <p>
    Your email address has been confirmed. You can close this window or go to
    <a href="{% url 'bid_main:index' %}">the Dashboard</a>.
  </p>
</div>{% endblock %}
{% block footer_scripts %}
{{ super }}
<script>
  var poll_url = '{% url 'bid_main:confirm-email-poll' %}';
  var $result = $('#poll_result');
  
  function poll() {
  	$.get(poll_url)
  	.done(function(data) {
  		if (typeof(data.confirmed) === 'undefined' || data.confirmed == null) {
  			// Not yet confirmed, wait longer
  			window.setTimeout(poll, 2500);
  			return;
  		}
  		// Confirmation has been confirmed!
  		$('#poll_ok').show();
  	})
  	.fail(function(err) {
  		// This is a frequent poll and the email address confirmation system works
  		// fine without it, so let's not bother the user with error messages.
  		if (console) console.log('Error: ', err);
  
  		// Try again after a while.
  		window.setTimeout(poll, 4000);
  	});
  }
  // Do a quick test first, then slow down a little bit.
  window.setTimeout(poll, 250);
</script>{% endblock footer_scripts %}

templates/bid_main/confirm_email/smtp_error.html
{% extends 'bid_main/confirm_email/base.html' %}
{% block confirm_email_body %}
<h1 class="text-danger">Error sending an email</h1>
<p>
  We couldn't send an email to {{ user.email }} for some reason. This most likely is due to
  something going wrong on our side. Don't worry, the error has been logged and will be handled
  soon.
  
</p>
<p>
  If you want you can try again to see if that helps.
  
</p>
<form action="{% url 'bid_main:confirm-email' %}" method="POST">{% csrf_token %}
  <div class="bid-cta"><a class="btn" href="{% url 'bid_main:index' %}">Back to the dashboard</a>
    <button class="btn btn-success" type="submit">Try again</button>
  </div>
</form>{% endblock %}

templates/bid_main/confirm_email/start.html
{% extends 'bid_main/confirm_email/form.html' %}
{% block confirm_email_above_form %}
<h1>Confirm your email address</h1>
<p>
  Before you can log in on another website with your KDE Identity, we have to verify your
  email address.
  
</p>
<p>
  Your email address is used to regain access to your account when you forget or reset your
  password. By confirming your email address, we can ensure this account actually belongs to you.
  
</p>{% endblock %}

templates/bid_main/confirm_email/start_for_oauth.html
{% extends 'bid_main/confirm_email/form.html' %}
{% block confirm_email_above_form %}
<h1>Confirm your email address</h1>
<p>Before you can log in at <strong>{{ next_name }}</strong> with your KDE Identity, we have to verify your
  email address.
  
</p>
<p>
  Your email address is used to regain access to your account when you forget or reset your
  password. By confirming your email address, we can ensure this account actually belongs to you.
  
</p>{% endblock %}

templates/bid_main/confirm_email/verified-expired.html
{% extends 'bid_main/confirm_email/form.html' %}
{% block confirm_email_above_form %}
<h1 class="text-danger">Link Expired</h1>
<p>The link you used to verify your email address was more than 12 hours old.</p>
<p>Let's try it again.</p>{% endblock %}

templates/bid_main/confirm_email/verified-happy.html
{% extends 'bid_main/confirm_email/base.html' %}
{% load static %}
{% block header %}
{{ super }}
<script src="{% static 'assets_vendor/js/js.cookie.min.js' %}"></script>
<script src="{% static 'assets/js/notifications.min.js' %}"></script>{% endblock %}
{% block confirm_email_body %}
<h1>Welcome back</h1>
<p class="hide-after-post">We are storing your confirmed email, please wait. If nothing happens for more than 5 seconds, press the button below.</p>
<div id="result"></div>
<p class="hide-after-post">
  <button class="enable-after-delay btn" disabled="disabled">Retry</button>
</p>
<p class="show-after-ok" style="display: none">Congratulations, you have successfully confirmed your email address.</p>
<p class="show-after-ok" style="display: none"><a class="btn btn-success" href="{{ next_url }}">Go to {{ next_name }}</a></p>{% endblock %}
{% block footer_scripts %}
<script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script>
  var csrftoken = Cookies.get('csrftoken');
  
  function enable_button() {
  	$('.enable-after-delay').removeAttr('disabled', '').on('click', do_post);
  }
  window.setTimeout(enable_button, 1500);
  
  function do_post() {
  	$('#result').html('');
  
  	$.ajax({
  		type: "POST",
  		url: window.location.href,
  		data: {
  			csrfmiddlewaretoken: csrftoken
  		},
  	})
  	.done(function() {
  		$('.hide-after-post').hide();
  		$('.show-after-ok').show();
  	})
  	.fail(function(err) {
  		var $p = $('<p>')
  			.addClass('text-danger')
  			.text(xhrErrorResponseMessage(err));
  		$('#result').html($p);
  		if (err.responseJSON.reload === true) {
  			// The verification failed, just reload to see it rendered on the GET request.
  			window.location.reload();
  		}
  	})
  	;
  }
  do_post();
</script>{% endblock %}

templates/bid_main/confirm_email/verified-invalid.html
{% extends 'bid_main/confirm_email/form.html' %}
{% block confirm_email_above_form %}
<h1 class="text-danger">Invalid Request</h1>
<p>Somehow there was a mismatch between the link we sent and the link you visited just now.</p>
<p>Let's try it again.</p>{% endblock %}

templates/bid_main/confirm_email/verified-other-account.html
{% extends 'bid_main/confirm_email/base.html' %}
{% block confirm_email_body %}
<h1 class="text-danger">For another account</h1>
<p>
  You are now logged in as {{ user.email }}, but the confirmation link was for {{ payload.e }}.
  
</p>
<p>You may want to <a href="{% url 'bid_main:switch_user' payload.e %}?next={{ request.path|urlencode:'' }}">switch to another account</a>.
  
</p>{% endblock %}