bid_api/urls.py
from django.conf.urls import url

from .views import info, badger, create_user, authenticate

app_name = 'bid_api'
urlpatterns = [
    url(r'^user$', info.user_info, name='user'),
    url(r'^me$', info.user_info),
    url(r'^user/(?P<user_id>\d+)$', info.UserInfoView.as_view(), name='user-info-by-id'),
    url(r'^user/(?P<user_id>\d+)/avatar$', info.UserAvatarView.as_view(), name='user-avatar'),
    url(r'^badges/(?P<user_id>\d+)$', info.UserBadgeView.as_view(), name='user-badges-by-id'),
    url(r'^badges/(?P<user_id>\d+)/html$', info.BadgesHTMLView.as_view(), name='user-badges-html'),
    url(r'^badges/(?P<user_id>\d+)/html/(?P<size>[a-z])$', info.BadgesHTMLView.as_view(),
        name='user-badges-html'),
    url(r'^stats$', info.StatsView.as_view(), name='stats'),
    url(r'^badger/grant/(?P<badge>[^/]+)/(?P<email_or_uid>[^/]+)$',
        badger.BadgerView.as_view(action='grant'), name='badger_grant'),
    url(r'^badger/revoke/(?P<badge>[^/]+)/(?P<email_or_uid>[^/]+)$',
        badger.BadgerView.as_view(action='revoke'), name='badger_revoke'),
    url(r'^check-user/(?P<email>[^/]+)$', create_user.CheckUserView.as_view(), name='check_user'),
    url(r'^create-user/?$', create_user.CreateUserView.as_view(), name='create_user'),
    url(r'^authenticate/?$', authenticate.AuthenticateView.as_view(), name='authenticate'),
]

# noinspection PyUnresolvedReferences
from . import signals as _

bid_main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from . import forms
from .views import normal_pages, registration_email, json_api

app_name = 'bid_main'
urlpatterns = [
    url(r'^$', normal_pages.IndexView.as_view(), name='index'),
    url(r'^settings/profile$', normal_pages.ProfileView.as_view(), name='profile'),
    url(r'^login$', normal_pages.LoginView.as_view(), name='login'),
    url(r'^logout$', normal_pages.LogoutView.as_view(next_page='bid_main:about'), name='logout'),
    url(r'^switch/?$', normal_pages.SwitchUserView.as_view(), name='switch_user'),
    url(r'^switch/(?P<switch_to>.+)$', normal_pages.SwitchUserView.as_view(), name='switch_user'),
    url(r'^privacy-policy/agree$', normal_pages.PrivacyPolicyAgreeView.as_view(),
        name='privacy_policy_agree'),

    url(r'^badge-toggle-private', json_api.BadgeTogglePrivateView.as_view(),
        name='badge_toggle_private'),

    url('^change$',
        auth_views.PasswordChangeView.as_view(
            form_class=forms.PasswordChangeForm,
            success_url=reverse_lazy('bid_main:password_change_done')),
        name='password_change'),
    url('^change-password/done$', auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    url(r'^password_reset/$',
        auth_views.PasswordResetView.as_view(
            form_class=forms.PasswordResetForm,
            success_url=reverse_lazy('bid_main:password_reset_done')),
        name='password_reset'),
    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('bid_main:password_reset_complete')),
        name='password_reset_confirm'),
    url(r'^password_reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    # Source of registration machinery:
    # http://musings.tinbrain.net/blog/2014/sep/21/registration-django-easy-way/
    url(r'^register/$', registration_email.RegistrationView.as_view(), name='register'),
    url(r'^register/signed-up/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/initial_signed_up.html'),
        name='register-done'),
    url(
        r'^register/password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        registration_email.InitialSetPasswordView.as_view(), name='register-confirm'),
    url(r'^register/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/registration_complete.html'),
        name='register-complete'),

    url(r'^confirm-email/start$',
        registration_email.ConfirmEmailView.as_view(),
        name='confirm-email'),
    url(r'^confirm-email/start-change$', registration_email.ConfirmEmailView.as_view(
        template_name='bid_main/confirm_email/change.html'), name='confirm-email-change'),
    url(r'^confirm-email/cancel-change$', registration_email.CancelEmailChangeView.as_view(),
        name='cancel-email-change'),
    url(r'^confirm-email/sent$',
        registration_email.ConfirmEmailSentView.as_view(),
        name='confirm-email-sent'),
    url(r'^confirm-email/verified/(?P<info>[^/]+)/(?P<hmac>[^/]+)$',
        registration_email.ConfirmEmailVerifiedView.as_view(),
        name='confirm-email-verified'),
    url(r'^confirm-email/poll$',
        registration_email.ConfirmEmailPollView.as_view(),
        name='confirm-email-poll'),
]

# Only enable this on a dev server:
if settings.DEBUG:
    from .views import testviews

    urlpatterns += [
        url(r'^debug/email-changed$', testviews.test_mail_email_changed),
        url(r'^debug/email-verify$', testviews.test_mail_verify_address),
        url(r'^error/(?P<code>\d+)$', testviews.test_error),
    ]

mykdeorg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.flatpages import views as fp_views
from django.conf import settings
import django.contrib.staticfiles.views

import bid_main.views.errors as error_views

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include('loginas.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('bid_addon_support.urls', namespace='addon_support')),
    url(r'^oauth/', include('mykdeorg.oauth2_urls', namespace='oauth2_provider')),
    url(r'^api/', include('bid_api.urls', namespace='bid_api')),
    url(r'', include('bid_main.urls', namespace='bid_main')),
]

handler400 = error_views.ErrorView.as_view(template_name='errors/400.html', status=400)
handler403 = error_views.ErrorView.as_view(template_name='errors/403.html', status=403)
handler404 = error_views.ErrorView.as_view(template_name='errors/404.html', status=404)
handler500 = error_views.ErrorView.as_view(template_name='errors/500.html', status=500)

if settings.DEBUG:
    import debug_toolbar

    settings.STATICFILES_FINDERS.insert(0, 'bid_main.devserver_support.MediaFinder')
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(rf'^media/(?P<path>.*)$', django.contrib.staticfiles.views.serve),
    ]

urlpatterns += [
    # Flatpages must be last!
    url(r'^(?P<url>.*/?)', fp_views.flatpage),
]

templates/_footer.html
<footer id="kFooter" class="footer">
    <section id="kFooterIncome" class="container">
        <div id="kDonateForm">
            <div class="center">
                <h3>Donate to KDE <a href="/community/donations/index.php#money" target="_blank">Why Donate?</a></h3>
                <form action="https://www.paypal.com/en_US/cgi-bin/webscr" method="post" onsubmit="return amount.value >= 2 || window.confirm('Your donation is smaller than 2€. This means that most of your donation\nwill end up in processing fees. Do you want to continue?');">
                        <input type="hidden" name="cmd" value="_donations">
                        <input type="hidden" name="lc" value="GB">
                        <input type="hidden" name="item_name" value="Development and communication of KDE software">
                        <input type="hidden" name="custom" value="//kde.org//donation_box">
                        <input type="hidden" name="currency_code" value="EUR">
                        <input type="hidden" name="cbt" value="Return to kde.org">
                        <input type="hidden" name="return" value="https://kde.org/community/donations/thanks_paypal">
                        <input type="hidden" name="notify_url" value="https://kde.org/community/donations/notify.php">
                        <input type="hidden" name="business" value="kde-ev-paypal@kde.org">
                        <input aria-label="Donation value" type="text" name="amount" value="20.00" id="donateAmountField" data-kpxc-id="donateAmountField"> €
                        <button type="submit" id="donateSubmit">Donate via PayPal</button>
                </form>

                <a href="/community/donations/others" id="otherWaysDonate" target="_blank">Other ways to donate</a>
            </div>
        </div>
        <div id="kMetaStore">
            <div class="center">
                <h3>Visit the KDE MetaStore</h3>
                <p>Show your love for KDE! Purchase books, mugs, apparel, and more to support KDE.</p>
                <a href="/stuff/metastore" class="button">Click here to browse</a>
            </div>
        </div>
    </section>

    <section id="kLinks" class="container">
        <div class="row">
            <nav class="col-sm">
                <h3>Products</h3>
                <a href="/plasma-desktop">Plasma</a>
                <a href="/applications/">KDE Applications</a>
                <a href="/products/frameworks/">KDE Frameworks</a>
                <a href="https://plasma-mobile.org/overview/">Plasma Mobile</a>
                <a href="https://neon.kde.org/">KDE neon</a>
                <a href="https://wikitolearn.org/" target="_blank">WikiToLearn</a>
            </nav>

            <nav class="col-sm">
                <h3>Develop</h3>
                <a href="https://techbase.kde.org/">TechBase Wiki</a>
                <a href="https://api.kde.org/">API Documentation</a>
                <a href="https://doc.qt.io/" target="_blank">Qt Documentation</a>
                <a href="https://inqlude.org/" target="_blank">Inqlude Documentation</a>
                <a href="/goals">Goals</a>
            </nav>

            <nav class="col-sm">
                <h3>News &amp; Press</h3>
                <a href="/announcements/">Announcements</a>
                <a href="https://dot.kde.org/">KDE.news</a>
                <a href="https://planetkde.org/">Planet KDE</a>
                <a href="https://www.kde.org/screenshots">Screenshots</a>
                <a href="https://www.kde.org/contact/">Press Contact</a>
            </nav>

            <nav class="col-sm">
                <h3>Resources</h3>
                <a href="https://community.kde.org/Main_Page">Community Wiki</a>
                <a href="https://userbase.kde.org/">UserBase Wiki</a>
                <a href="/stuff/">Miscellaneous Stuff</a>
                <a href="/support/">Support</a>
                <a href="/support/international.php">International Websites</a>
                <a href="/download/">Download KDE Software</a>
                <a href="/code-of-conduct/">Code of Conduct</a>
                <a href="/privacypolicy">Privacy Policy</a>
                <a href="/privacypolicy-apps">Applications Privacy Policy</a>
            </nav>

            <nav class="col-sm">
                <h3>Destinations</h3>
                <a href="https://store.kde.org/">KDE Store</a>
                <a href="https://ev.kde.org/">KDE e.V.</a>
                <a href="https://www.kde.org/community/whatiskde/kdefreeqtfoundation.php">KDE Free Qt Foundation</a>
                <a href="https://timeline.kde.org/">KDE Timeline</a>
            </nav>
        </div>
    </section>

    <section id="kSocial" class="container kSocialLinks">
        <!-- <nav style="position: absolute; left: 15px;">
            Browsing in English (Languages coming soon)
        </nav> -->

        <a class="shareFacebook" href="https://www.facebook.com/kde/" rel="nofollow">Post on Facebook</a>
        <a class="shareTwitter" href="https://twitter.com/kdecommunity" rel="nofollow">Share on Twitter</a>
        <a class="shareDiaspora" href="https://joindiaspora.com/people/9c3d1a454919ef06" rel="nofollow">Share on Diaspora</a>
        <a class="shareMastodon" href="https://mastodon.technology/@kde" rel="me nofollow">Share on Mastodon</a>
        <a class="shareLinkedIn" href="https://www.linkedin.com/company/29561/" rel="nofollow">Share on LinkedIn</a>
        <a class="shareReddit" href="https://www.reddit.com/r/kde/" rel="nofollow">Share on Reddit</a>
        <a class="shareYouTube" href="https://www.youtube.com/channel/UCF3I1gf7GcbmAb0mR6vxkZQ" rel="nofollow">Share on YouTube</a>
        <a class="sharePeerTube" href="https://peertube.mastodon.host/accounts/kde/videos" rel="nofollow">Share on PeerTube</a>
        <a class="shareVK" href="https://vk.com/kde_ru" rel="nofollow">Share on VK</a>
    </section>

    <section id="kLegal" class="container">
        <div class="row">
            <small class="col-4">
                Maintained by <a href="mailto:kde-webmaster@kde.org">KDE Webmasters</a>
            </small>
            <small class="col-8" style="text-align: right;">
                KDE<sup>®</sup> and <a href="/media/images/trademark_kde_gear_black_logo.png">the K Desktop Environment<sup>®</sup> logo</a> are registered trademarks of <a href="https://ev.kde.org/" title="Homepage of the KDE non-profit Organization">KDE e.V.</a> |
                <a href="https://www.kde.org/community/whatiskde/impressum">Legal</a>
            </small>
        </div>
    </section>
</footer>

templates/_navbar.html
<header id="KGlobalHeader" class="header clearfix">
  <nav class="navbar navbar-expand">
    <a aria-label="KDE Homepage" class="kde-logo navbar-brand active" href="/">KDE Accounts</a>
    {% if user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{{ settings.LOGOUT_URL }}">Log out</a>
          </li>
        </ul>
      </div>
    {% endif %}
  </nav>
</header>

templates/email_layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{{ subject }}{% endblock %}</title>
    <style>
      html, body {
      	background-color: white;
      	color: black;
      	font-family: 'Roboto', 'Noto Sans', sans-serif;
      	font-size: 10pt;
      }
      
      body {
      	max-width: 100%;
      	width: 60ex;
      	margin-right: auto;
      	padding: 0.5em 1em;
      }
      
      p {
      	line-height: 150%;
      }
      p.closing {
      	margin-top: 3.5em;
      }
      
      section.about {
      	margin-top: 2em;
      	color: #888;
      }
    </style>
  </head>
  <body>{% block body %}{% endblock %}
    <p class="closing">Kind regards,</p>
    <p>The Blender web team</p>
  </body>
</html>

templates/layout.html
{% load static %}
{% load flatpages %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block page_title %}Home{% endblock %} - KDE Accounts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="KDE Accounts is a unified login system for all services around KDE.">
    <meta name="author" content="Blender Foundation, KDE">
    <link href="https://cdn.kde.org/aether-devel/bootstrap.css" rel="stylesheet">
    <link href="https://cdn.kde.org/aether-devel/aether-kde-org.css" rel="stylesheet">
    <script src="https://cdn.kde.org/aether-devel/bootstrap.js" defer=""></script>
  </head>
  <body>
    {% block modal %}
    {% endblock %}

    {% block navigation_header %}
      {% include "_navbar.html" %}
    {% endblock navigation_header %}

    {% block header %} {% endblock %}

    <div class="alert alert-danger container">
      This is a test instance. Please don't use it and use <a href="https://identity.kde.org">KDE Identity</a> instead.
      Interested in the development of this application, join us in #kde-www or <a href="https://community.kde.org/Telegram#Development">Telegram</a>.
    </div>

    {% for message in messages %}
    <div class="alert alert-info {{ message.tags }}">
      <div class="container">
        {{ message }}
        <button class="close" type="button" data-dismiss="alert">Close</button>
      </div>
    </div>
    {% endfor %}

    <div class="container">
      {% if user and user.must_pp_agree %}
        {% block privacy_policy_banner %}
        <div class="privacy-policy-must-agree bid box">
          <h1>Our Privacy Policy Changed</h1>
          <p>In order to continue using KDE Accounts, please accept <a href="{% url 'bid_main:privacy_policy_agree' %}">our new privacy policy</a>.</p>
        </div>
        {% endblock %}
      {% endif %}
      <div class="container mt-3">
        <div class="row justify-content-center">
          <div class="col-md-10">
            {% block body %}{% endblock %}
          </div>
        </div>
      </div>
    </div>
    {% block footer_scripts %}{% endblock footer_scripts %}

    {% block footer %}
      {% include "_footer.html" %}
    {% endblock footer %}
  </body>
</html>